server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway

  cloud:
    gateway:

      # ✅ CORS (OBLIGATOIRE POUR ANGULAR)
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      # ✅ ROUTING
      routes:
        - id: surveillance
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/surveillance/**
        - id: maintenance
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/maintenance/**

      # (optionnel si tu n'utilises pas Eureka)
      discovery:
        locator:
          enabled: false
