eureka:
  instance:
    hostname: eureka-serve
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


server:
  port: 8090
spring:
  rabbitmq:
    host: 192.168.10.161
    port: 5672
    username: uptech
    password: uptech
  application:
    name: surveillance
  datasource:
    url: jdbc:mysql://192.168.10.161:3306/surveillance?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      data-source-properties:
        serverTimezone: UTC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: UTC

management:
  zipkin:
    tracing:
      enabled: false